#! /bin/zsh

# Screen Padding
bspc config top_padding 36
bspc config left_padding 8
bspc config right_padding 8
bspc config bottom_padding 8

bspc config border_width 4
bspc config window_gap 16
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config adaptive_raise true
bspc config auto_cancel true

bspc monitor -d 1 2 3 4 5 6

bspc rule -a Firefox desktop=^4
bspc rule -a mupdf window=pseudo_tiled
bspc rule -a Gimp desktop=^3 follow=on floating=on

sleep 2
~/.config/bspwm/panel/panel &
